/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 4, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 
*/

/* SOLUTION
We can approach this problem in two ways. The general approach involves iterating through each fibonacci term (until we reach 4 million), 
checking if it is divisible by 2 (i.e. if it is even), and adding it to the sum.
An alternative approach is to leverage the property of fibonacci series, that every 3rd term starting from 2 is even. Thus instead of iterating through all 
the terms, we can directly generate the even terms and add them.

This is the series: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ...
We can start with the 2nd term, which is 2, and then jump directly to 8, then 34, and then 144. Thus, the new sequence becomes: 2, 8, 34, 144.

We can observe a pattern here: 4*8+2 = 34, similarly 4*34+8 = 144
Therefore, we need to initialize the first two even terms, i.e. 2 and 8. Then we calculate the subsequent even terms using the relation.
Since we have initialized the first two even terms, we initialize the sum to 2+8=10. 
*/


#include<stdio.h>
int main()
{
	int a=2, b=8, sum=10;
	while(1){
		int fib = 4*b+a;
		if(fib>4000000)
			break;
		a=b;
		b=fib;
		sum+=fib;
	}
	printf("%d", sum);
	return 0;
}


// GENERAL APPROACH

// #include<stdio.h>
// int main()
// {
// 	int a=1, b=2, sum=2;
// 	for(int i=3; fib<=4000000; i++){
// 		int fib = a+b; 
// 		a=b; 
// 		b=fib;
// 		if(fib%2==0)
// 			sum+=fib; 
// 	}
// 	printf("%d", sum);
// 	return 0;
// }


